"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Building2, CalendarDays, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { fundamentals } from "@/lib/demo-data";

function MetricGrid({data}:{data:string[][]}){return <div className="grid gap-3 sm:grid-cols-2">{data.map(([label,value,helper])=><div key={label} className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="metric-number mt-2 text-xl font-medium">{value}</p><p className="mt-1 text-xs text-muted-foreground">{helper}</p></div>)}</div>}
export function FundamentalsView(){const[query,setQuery]=useState("WEGE3");const[shown,setShown]=useState("WEGE3");return <>
  <Card className="mb-6 shadow-none"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value.toUpperCase())} placeholder="Digite um ticker, ex.: WEGE3" className="pl-9"/></div><Button onClick={()=>setShown(query||"WEGE3")}>Consultar</Button></CardContent></Card>
  <div className="grid gap-6 xl:grid-cols-[300px_minmax(0,1fr)]"><Card className="h-fit shadow-none"><CardContent className="p-6"><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary"><Building2 className="size-5"/></span><p className="mt-5 font-mono text-sm text-primary">{shown}</p><h2 className="mt-1 text-xl font-medium">{shown==="WEGE3"?fundamentals.company:"Empresa selecionada"}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{fundamentals.sector}</p><div className="mt-6 border-t pt-5"><p className="text-xs text-muted-foreground">Preço</p><p className="metric-number mt-1 text-2xl">{fundamentals.price}</p><p className="mt-4 text-xs text-muted-foreground">Valor de mercado</p><p className="metric-number mt-1">{fundamentals.marketCap}</p></div><div className="mt-6 flex items-center gap-2 text-xs text-muted-foreground"><CalendarDays className="size-4"/>Referência: {fundamentals.updatedAt}</div><Button variant="outline" className="mt-6 w-full" asChild><Link href="/backtests">Testar este ativo <ArrowRight className="size-4"/></Link></Button></CardContent></Card>
  <Card className="shadow-none"><CardHeader><CardTitle>Qualidade e preço</CardTitle><CardDescription>Compare múltiplos ao próprio histórico e rentabilidade ao setor.</CardDescription></CardHeader><CardContent><Tabs defaultValue="valuation"><TabsList><TabsTrigger value="valuation">Valuation</TabsTrigger><TabsTrigger value="profit">Rentabilidade</TabsTrigger><TabsTrigger value="debt">Dívida e caixa</TabsTrigger><TabsTrigger value="growth">Crescimento</TabsTrigger></TabsList><TabsContent value="valuation" className="mt-6"><MetricGrid data={fundamentals.valuation}/></TabsContent><TabsContent value="profit" className="mt-6"><MetricGrid data={fundamentals.profitability}/></TabsContent><TabsContent value="debt" className="mt-6"><MetricGrid data={[["Dívida líquida/EBITDA","−0,3×","Caixa líquido"],["Cobertura de juros","18,4×","Confortável"],["Dívida bruta","R$ 4,1 bi","−6% a/a"],["Caixa","R$ 6,8 bi","+11% a/a"]]}/></TabsContent><TabsContent value="growth" className="mt-6"><MetricGrid data={[["Receita CAGR 5a","18,7%","Acima do setor"],["Lucro CAGR 5a","22,1%","Consistente"],["Receita a/a","+14,2%","Últimos 12 meses"],["Lucro a/a","+19,8%","Últimos 12 meses"]]}/></TabsContent></Tabs><p className="mt-6 rounded-xl bg-muted p-4 text-xs leading-5 text-muted-foreground">Indicadores são informativos e podem conter defasagem. Sempre confira a data de referência e os documentos da companhia.</p></CardContent></Card></div>
  </>}
