"use client";
import { useMemo, useState } from "react";
import { Copy, Download, MoreHorizontal, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { recentRuns } from "@/lib/demo-data";

export function HistoryView(){const[q,setQ]=useState("");const[selected,setSelected]=useState<string[]>([]);const[deleted,setDeleted]=useState<string[]>([]);const rows=useMemo(()=>recentRuns.filter(r=>!deleted.includes(r.id)&&(`${r.name} ${r.id} ${r.mode}`).toLowerCase().includes(q.toLowerCase())),[q,deleted]);const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);return <>
  <Card className="mb-5 shadow-none"><CardContent className="grid gap-3 p-4 md:grid-cols-[1fr_200px_200px_auto]"><div className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar nota, ticker, modo ou ID" className="pl-9"/></div><Select defaultValue="all"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos os modos</SelectItem><SelectItem value="portfolio">Carteira</SelectItem><SelectItem value="asset">Por ativo</SelectItem><SelectItem value="optimizer">Otimizador</SelectItem></SelectContent></Select><Select defaultValue="30"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="7">Últimos 7 dias</SelectItem><SelectItem value="30">Últimos 30 dias</SelectItem><SelectItem value="all">Todo o período</SelectItem></SelectContent></Select><Button variant="outline" disabled={selected.length<2} onClick={()=>toast.success("Comparação aberta.")}>Comparar ({selected.length})</Button></CardContent></Card>
  <Card className="shadow-none"><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead className="w-12"><span className="sr-only">Selecionar</span></TableHead><TableHead>Execução</TableHead><TableHead>Modo</TableHead><TableHead>Data</TableHead><TableHead className="text-right">Retorno</TableHead><TableHead className="text-right">Sharpe</TableHead><TableHead>Status</TableHead><TableHead><span className="sr-only">Ações</span></TableHead></TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.id} data-state={selected.includes(r.id)?"selected":undefined}><TableCell><Checkbox checked={selected.includes(r.id)} onCheckedChange={()=>toggle(r.id)} aria-label={`Selecionar ${r.id}`}/></TableCell><TableCell><strong className="block text-sm">{r.name}</strong><span className="font-mono text-[11px] text-muted-foreground">{r.id}</span></TableCell><TableCell>{r.mode}</TableCell><TableCell className="text-muted-foreground">{r.date}</TableCell><TableCell className="text-right text-success">{r.return}</TableCell><TableCell className="text-right">{r.sharpe}</TableCell><TableCell><Badge variant="outline">{r.status}</Badge></TableCell><TableCell><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost" aria-label={`Ações de ${r.id}`}><MoreHorizontal className="size-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>toast.success("Configuração duplicada.")}><Copy/>Duplicar</DropdownMenuItem><DropdownMenuItem onClick={()=>toast.success("Relatório preparado.")}><Download/>Exportar</DropdownMenuItem><AlertDialog><AlertDialogTrigger asChild><DropdownMenuItem variant="destructive" onSelect={e=>e.preventDefault()}><Trash2/>Excluir</DropdownMenuItem></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir {r.id}?</AlertDialogTitle><AlertDialogDescription>O resultado e seus artefatos serão removidos. Esta ação não pode ser desfeita.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={()=>setDeleted(d=>[...d,r.id])}>Excluir execução</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
  </>}
