"use client";

import { useState } from "react";
import { AlertTriangle, FlaskConical, Play, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { MetricCard } from "@/components/product/metric-card";
import { optimizerRows } from "@/lib/demo-data";

export function OptimizerLab() {
  const [running,setRunning]=useState(false); const [done,setDone]=useState(true); const [validation,setValidation]=useState("walk");
  const run=()=>{setRunning(true);setDone(false);setTimeout(()=>{setRunning(false);setDone(true);toast.success("81 combinações validadas.")},900)};
  return <div className="grid gap-6 xl:grid-cols-[380px_minmax(0,1fr)]">
    <Card className="h-fit shadow-none"><CardHeader><CardTitle>Espaço de busca</CardTitle><CardDescription>Intervalos inclusivos; 81 combinações estimadas.</CardDescription></CardHeader><CardContent className="space-y-6">
      {[{name:"Entrada RSI",min:5,max:15,step:5},{name:"Saída RSI",min:65,max:75,step:5},{name:"Máximo de barras",min:5,max:9,step:2}].map(p=><fieldset key={p.name} className="rounded-xl border p-4"><legend className="px-1 text-sm font-medium">{p.name}</legend><div className="mt-2 grid grid-cols-3 gap-2">{[["Mín.",p.min],["Máx.",p.max],["Passo",p.step]].map(([l,v])=><div key={String(l)}><Label className="text-[11px] text-muted-foreground">{l}</Label><Input type="number" defaultValue={v}/></div>)}</div></fieldset>)}
      <div><Label className="mb-3 block">Validação</Label><RadioGroup value={validation} onValueChange={setValidation} className="space-y-2"><label className="flex min-h-14 cursor-pointer gap-3 rounded-xl border p-3"><RadioGroupItem value="walk" className="mt-0.5"/><span><strong className="block text-sm">Walk-forward</strong><span className="text-xs text-muted-foreground">Janela crescente, 5 folds</span></span></label><label className="flex min-h-14 cursor-pointer gap-3 rounded-xl border p-3"><RadioGroupItem value="split" className="mt-0.5"/><span><strong className="block text-sm">IS/OOS fixo</strong><span className="text-xs text-muted-foreground">70% treino · 30% teste</span></span></label></RadioGroup></div>
      <Button className="w-full" onClick={run} disabled={running}><Play className="size-4"/>{running?"Validando…":"Executar 81 combinações"}</Button>{running?<Progress value={64}/>:null}
    </CardContent></Card>
    <div className="space-y-6">{done?<><div className="flex items-center justify-between"><div><h2 className="text-xl font-medium">Resultado da validação</h2><p className="mt-1 text-sm text-muted-foreground">Objetivo: maior Sharpe fora da amostra</p></div><Badge className="bg-success text-white"><ShieldCheck className="size-3.5"/>Estável</Badge></div><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Melhor entrada" value="RSI < 10"/><MetricCard label="Melhor saída" value="RSI > 70"/><MetricCard label="Sharpe OOS" value="1,18" tone="positive" delta="vs. 1,41 IS"/><MetricCard label="Degradação" value="−16,3%" tone="negative" delta="Aceitável"/></section><Card className="shadow-none"><CardHeader><CardTitle>Sensibilidade dos parâmetros</CardTitle><CardDescription>Sharpe por entrada e saída. Células vizinhas semelhantes sugerem robustez.</CardDescription></CardHeader><CardContent><div className="grid grid-cols-4 gap-2 text-center text-xs"><span/><span>Saída 65</span><span>Saída 70</span><span>Saída 75</span>{[5,10,15].map(entry=><div key={entry} className="contents"><span className="grid place-items-center text-muted-foreground">Entrada {entry}</span>{optimizerRows.filter(r=>r.rsi===entry).map(r=><div key={`${r.rsi}-${r.exit}`} className={`rounded-lg p-4 font-mono ${r.sharpe>=1.3?"bg-primary text-primary-foreground":r.sharpe>=1.1?"bg-primary/20":"bg-muted"}`}>{r.sharpe.toFixed(2)}</div>)}</div>)}</div></CardContent></Card><Card className="shadow-none"><CardHeader><CardTitle>Ranking fora da amostra</CardTitle></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Entrada</TableHead><TableHead>Saída</TableHead><TableHead className="text-right">Retorno</TableHead><TableHead className="text-right">Sharpe</TableHead><TableHead className="text-right">Max DD</TableHead></TableRow></TableHeader><TableBody>{optimizerRows.slice().sort((a,b)=>b.sharpe-a.sharpe).slice(0,5).map(r=><TableRow key={`${r.rsi}-${r.exit}`}><TableCell>RSI &lt; {r.rsi}</TableCell><TableCell>RSI &gt; {r.exit}</TableCell><TableCell className="text-right text-success">+{r.return}%</TableCell><TableCell className="text-right">{r.sharpe}</TableCell><TableCell className="text-right text-destructive">{r.maxdd}%</TableCell></TableRow>)}</TableBody></Table></CardContent></Card><div className="flex gap-3 rounded-xl border border-warning/30 bg-warning/5 p-4 text-sm"><AlertTriangle className="size-5 shrink-0 text-warning"/><p>Há perda moderada entre treino e teste. A região 10/70 é estável, mas deve ser validada em outro universo antes do uso real.</p></div></>:<Card className="shadow-none"><CardContent className="grid min-h-96 place-items-center text-center"><div><FlaskConical className="mx-auto size-8 animate-pulse text-primary"/><p className="mt-4 font-medium">Executando validação sem vazamento…</p></div></CardContent></Card>}</div>
  </div>;
}
