"use client";
import { useState } from "react";
import { CheckCircle2, Database, Save } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { PageHeader } from "@/components/product/page-header";

export default function SettingsPage(){const[testing,setTesting]=useState(false);return <><PageHeader eyebrow="Preferências" title="Dados e configurações" description="Centralize fonte, moeda, fuso e retenção. Segredos permanecem fora do navegador."/><div className="grid gap-6 xl:grid-cols-2"><Card className="shadow-none"><CardHeader><CardTitle>Fonte de dados</CardTitle><CardDescription>O frontend usa amostras locais até uma API ser configurada.</CardDescription></CardHeader><CardContent className="space-y-5"><div><Label>API RSI2</Label><Input className="mt-2" defaultValue="http://localhost:8000"/></div><div><Label>Provedor de mercado</Label><Select defaultValue="norgate"><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="norgate">Norgate Data</SelectItem><SelectItem value="csv">Diretório CSV</SelectItem><SelectItem value="demo">Dados demonstrativos</SelectItem></SelectContent></Select></div><Button variant="outline" onClick={()=>{setTesting(true);setTimeout(()=>{setTesting(false);toast.success("Contrato da API validado.")},500)}}><Database className="size-4"/>{testing?"Testando…":"Testar conexão"}</Button><div className="flex gap-3 rounded-xl border border-success/30 bg-success/5 p-4 text-sm"><CheckCircle2 className="size-5 text-success"/><span>Esquema OpenAPI v1 compatível</span></div></CardContent></Card><Card className="shadow-none"><CardHeader><CardTitle>Experiência e retenção</CardTitle><CardDescription>Preferências locais para todas as pesquisas.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><div><Label>Moeda</Label><Select defaultValue="BRL"><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="BRL">BRL · Real</SelectItem><SelectItem value="USD">USD · Dólar</SelectItem></SelectContent></Select></div><div><Label>Fuso horário</Label><Select defaultValue="sp"><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="sp">America/São_Paulo</SelectItem><SelectItem value="ny">America/New_York</SelectItem><SelectItem value="utc">UTC</SelectItem></SelectContent></Select></div></div><div><Label>Reter execuções por</Label><Select defaultValue="365"><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="90">90 dias</SelectItem><SelectItem value="365">1 ano</SelectItem><SelectItem value="forever">Sem expiração</SelectItem></SelectContent></Select></div><label className="flex items-center justify-between rounded-xl border p-4"><span><strong className="block text-sm">Avisos metodológicos</strong><span className="text-xs text-muted-foreground">Exibir alertas de viés e overfitting.</span></span><Switch defaultChecked/></label><Button onClick={()=>toast.success("Preferências salvas.")}><Save className="size-4"/>Salvar preferências</Button></CardContent></Card></div></>}
